# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(verbose_name='article text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='image')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='published date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(verbose_name='article text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='image')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='published date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'feeder',
                'verbose_name_plural': 'feeders',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(verbose_name='article text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='image')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='published date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendation_articles',
            },
        ),
    ]
