# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie_talks', '0002_auto_20160513_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='pupil_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pupil age'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='pupil_name',
            field=models.CharField(default='', max_length=50, verbose_name='pupil name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeder',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='school'),
        ),
    ]
