# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie_talks', '0003_auto_20160514_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='pupil_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pupil name'),
        ),
    ]
