# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('your_feeders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourfeeder',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
