# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('greeting_text', models.TextField(verbose_name='greeting text')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'greeting',
                'verbose_name_plural': 'greetings',
            },
        ),
    ]
