# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_feeders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourfeeder',
            options={'ordering': ('title',), 'verbose_name': 'our feeder', 'verbose_name_plural': 'our feeders'},
        ),
        migrations.RemoveField(
            model_name='ourfeeder',
            name='pupil_age',
        ),
        migrations.RemoveField(
            model_name='ourfeeder',
            name='pupil_name',
        ),
        migrations.RemoveField(
            model_name='ourfeeder',
            name='school',
        ),
        migrations.AlterField(
            model_name='ourfeeder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_feeders/%Y/%m/%d', verbose_name='image'),
        ),
    ]
